db:
  username: ${username.value:postgres}
  password: root
  driver: PostgresDriver
  url: jdbc:postgresql://localhost:5432/spring_db
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring.profiles.active: qa
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
        jdbc:
          batch_size: 50
          fetch_size: 50
logging:
  level:
    root: info
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: trace